Naming/VariableNumber:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Metrics/BlockLength:
  Enabled: false
