Naming/VariableNumber:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
